apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "validacion-service.fullname" . }}-config
  labels:
    {{- include "validacion-service.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.env.SPRING_PROFILES_ACTIVE | default "default" | quote }}
  JAVA_OPTS: {{ .Values.env.JAVA_OPTS | default "-Xms256m -Xmx512m" | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | default "INFO" | quote }}
  SERVER_PORT: "8080"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
