apiVersion: v2
name: notificacion-service
description: Microservicio de Notificaciones - Consumidor Kafka
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - microservices
  - spring-boot
  - kafka
  - consumer
