server:
  port: 8083

spring:
  application:
    name: validacion-service

  # TODO: Descomentar y configurar Kafka Consumer
  # kafka:
  #   bootstrap-servers: localhost:9092
  #   consumer:
  #     group-id: validacion-group
  #     auto-offset-reset: earliest
  #     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #     value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
