apiVersion: v2
name: mutualidad-platform
description: Umbrella Chart - Plataforma completa de Mutualidad
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - microservices
  - spring-boot
  - kafka
  - mutualidad

maintainers:
  - name: Team Backend
    email: backend@mutualidad.com

dependencies:
  # Kafka
  - name: kafka
    version: 26.8.0
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled

  # PostgreSQL
  - name: postgresql
    version: 12.1.9
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

  # Microservicios (charts locales)
  - name: afiliado-service
    version: 0.1.0
    repository: "file://../afiliado-service-chart"
    condition: afiliado-service.enabled

  - name: notificacion-service
    version: 0.1.0
    repository: "file://../notificacion-service-chart"
    condition: notificacion-service.enabled

  - name: validacion-service
    version: 0.1.0
    repository: "file://../validacion-service-chart"
    condition: validacion-service.enabled
