global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Metricas del OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  # Metricas de los servicios Spring Boot (Actuator)
  - job_name: 'afiliado-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['afiliado-service:8081']

  - job_name: 'notificacion-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notificacion-service:8082']

  - job_name: 'validacion-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['validacion-service:8083']
