apiVersion: v2
name: afiliado-service
description: Microservicio de Afiliados - Productor Kafka
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - microservices
  - spring-boot
  - kafka
  - producer

maintainers:
  - name: Team Backend
    email: backend@mutualidad.com

dependencies:
  - name: postgresql
    version: 12.1.9
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
