server:
  port: 8081

spring:
  application:
    name: afiliado-service
  # TODO Ejercicio 1: Configurar conexion a Kafka
  # kafka:
  #   bootstrap-servers: localhost:9092
  #   producer:
  #     key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #     value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  #     properties:
  #       spring.json.add.type.headers: false
  #     acks: all
  #     retries: 3

# TODO Ejercicio 1: Configurar nombre del topic
# app:
#   kafka:
#     topic:
#       afiliado-eventos: afiliado-eventos

logging:
  level:
    com.mutualidad: DEBUG
    org.springframework.kafka: INFO
